/*
iam-api

REST API OpenAPI documentation for the iam-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iam/api/openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseTOTPDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseTOTPDevice{}

// ResponseTOTPDevice struct for ResponseTOTPDevice
type ResponseTOTPDevice struct {
	State string `json:"state"`
	Data TOTPDevice `json:"data"`
}

type _ResponseTOTPDevice ResponseTOTPDevice

// NewResponseTOTPDevice instantiates a new ResponseTOTPDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseTOTPDevice(state string, data TOTPDevice) *ResponseTOTPDevice {
	this := ResponseTOTPDevice{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseTOTPDeviceWithDefaults instantiates a new ResponseTOTPDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseTOTPDeviceWithDefaults() *ResponseTOTPDevice {
	this := ResponseTOTPDevice{}
	return &this
}

// GetState returns the State field value
func (o *ResponseTOTPDevice) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseTOTPDevice) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseTOTPDevice) SetState(v string) {
	o.State = v
}

// GetData returns the Data field value
func (o *ResponseTOTPDevice) GetData() TOTPDevice {
	if o == nil {
		var ret TOTPDevice
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseTOTPDevice) GetDataOk() (*TOTPDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseTOTPDevice) SetData(v TOTPDevice) {
	o.Data = v
}

func (o ResponseTOTPDevice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseTOTPDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResponseTOTPDevice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseTOTPDevice := _ResponseTOTPDevice{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseTOTPDevice)

	if err != nil {
		return err
	}

	*o = ResponseTOTPDevice(varResponseTOTPDevice)

	return err
}

type NullableResponseTOTPDevice struct {
	value *ResponseTOTPDevice
	isSet bool
}

func (v NullableResponseTOTPDevice) Get() *ResponseTOTPDevice {
	return v.value
}

func (v *NullableResponseTOTPDevice) Set(val *ResponseTOTPDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseTOTPDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseTOTPDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseTOTPDevice(val *ResponseTOTPDevice) *NullableResponseTOTPDevice {
	return &NullableResponseTOTPDevice{value: val, isSet: true}
}

func (v NullableResponseTOTPDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseTOTPDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


