openapi: 3.0.3
info:
  description: REST API OpenAPI documentation for the iam-api
  title: iam-api
  version: 1.0.0
servers:
- url: /
paths:
  /iam/mfa/totp:
    post:
      description: Create a new TOTP device for your account.
      operationId: createTotpDevice
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTOTPDevice'
          description: Created
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
          description: Not Found
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
          description: Not Found
        "406":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
          description: Not Acceptable
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
          description: Too Many Requests
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBadRequestTOTPDevice'
          description: Bad Request
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTOTPDevice'
          description: Accepted
      security:
      - {}
      summary: Create a TOTP device
      tags:
      - MFA - TOTP Device
components:
  schemas:
    DefaultErrorResponse:
      additionalProperties: false
      example:
        detail: detail
      properties:
        detail:
          type: string
      title: DefaultErrorResponse
      type: object
    ResponseBadRequestTOTPDevice:
      additionalProperties: false
      example:
        detail: detail
        url:
        - url
        - url
      properties:
        url:
          items:
            type: string
          type: array
        detail:
          type: string
      title: ResponseBadRequestTOTPDevice
      type: object
    ResponseTOTPDevice:
      additionalProperties: false
      example:
        data:
          url: url
        state: state
      properties:
        state:
          title: StateEnum
          type: string
        data:
          $ref: '#/components/schemas/TOTPDevice'
      required:
      - data
      - state
      title: ResponseTOTPDevice
      type: object
    StateEnum:
      title: StateEnum
      type: string
    TOTPDevice:
      additionalProperties: false
      example:
        url: url
      properties:
        url:
          maxLength: 255
          minLength: 0
          pattern: .*
          readOnly: true
          type: string
      required:
      - url
      title: TOTPDevice
      type: object
