/*
edge-api

Testing EdgeApplicationsCacheSettingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package edge

import (
	"context"
	"testing"

	openapiclient "github.com/aziontech/azionapi-v4-go-sdk/edge-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_edge_EdgeApplicationsCacheSettingsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EdgeApplicationsCacheSettingsAPIService CreateCacheSetting", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.CreateCacheSetting(context.Background(), edgeApplicationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdgeApplicationsCacheSettingsAPIService DestroyCacheSetting", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string
		var id string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.DestroyCacheSetting(context.Background(), edgeApplicationId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdgeApplicationsCacheSettingsAPIService ListCacheSettings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.ListCacheSettings(context.Background(), edgeApplicationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdgeApplicationsCacheSettingsAPIService PartialUpdateCacheSetting", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string
		var id string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.PartialUpdateCacheSetting(context.Background(), edgeApplicationId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdgeApplicationsCacheSettingsAPIService RetrieveCacheSetting", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string
		var id string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.RetrieveCacheSetting(context.Background(), edgeApplicationId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EdgeApplicationsCacheSettingsAPIService UpdateCacheSetting", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var edgeApplicationId string
		var id string

		resp, httpRes, err := apiClient.EdgeApplicationsCacheSettingsAPI.UpdateCacheSetting(context.Background(), edgeApplicationId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
