/*
edgesql-api

REST API OpenAPI documentation for the EdgeSQL API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgesql

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseDeleteDatabase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteDatabase{}

// ResponseDeleteDatabase struct for ResponseDeleteDatabase
type ResponseDeleteDatabase struct {
	State StateEnum `json:"state"`
	Data NullableDatabase `json:"data"`
}

type _ResponseDeleteDatabase ResponseDeleteDatabase

// NewResponseDeleteDatabase instantiates a new ResponseDeleteDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteDatabase(state StateEnum, data NullableDatabase) *ResponseDeleteDatabase {
	this := ResponseDeleteDatabase{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseDeleteDatabaseWithDefaults instantiates a new ResponseDeleteDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteDatabaseWithDefaults() *ResponseDeleteDatabase {
	this := ResponseDeleteDatabase{}
	return &this
}

// GetState returns the State field value
func (o *ResponseDeleteDatabase) GetState() StateEnum {
	if o == nil {
		var ret StateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseDeleteDatabase) GetStateOk() (*StateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseDeleteDatabase) SetState(v StateEnum) {
	o.State = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for Database will be returned
func (o *ResponseDeleteDatabase) GetData() Database {
	if o == nil || o.Data.Get() == nil {
		var ret Database
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseDeleteDatabase) GetDataOk() (*Database, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *ResponseDeleteDatabase) SetData(v Database) {
	o.Data.Set(&v)
}

func (o ResponseDeleteDatabase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteDatabase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data.Get()
	return toSerialize, nil
}

func (o *ResponseDeleteDatabase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseDeleteDatabase := _ResponseDeleteDatabase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseDeleteDatabase)

	if err != nil {
		return err
	}

	*o = ResponseDeleteDatabase(varResponseDeleteDatabase)

	return err
}

type NullableResponseDeleteDatabase struct {
	value *ResponseDeleteDatabase
	isSet bool
}

func (v NullableResponseDeleteDatabase) Get() *ResponseDeleteDatabase {
	return v.value
}

func (v *NullableResponseDeleteDatabase) Set(val *ResponseDeleteDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteDatabase(val *ResponseDeleteDatabase) *NullableResponseDeleteDatabase {
	return &NullableResponseDeleteDatabase{value: val, isSet: true}
}

func (v NullableResponseDeleteDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


