/*
edgesql-api

REST API OpenAPI documentation for the EdgeSQL API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgesql

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ResponseListDatabase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseListDatabase{}

// ResponseListDatabase struct for ResponseListDatabase
type ResponseListDatabase struct {
	Id int32 `json:"id"`
	Name string `json:"name" validate:"regexp=^[A-Za-z0-9-]{6,50}$"`
	ClientId string `json:"client_id"`
	Status *StatusEnum `json:"status,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt NullableTime `json:"deleted_at"`
	IsActive *bool `json:"is_active,omitempty"`
}

type _ResponseListDatabase ResponseListDatabase

// NewResponseListDatabase instantiates a new ResponseListDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseListDatabase(id int32, name string, clientId string, createdAt time.Time, updatedAt time.Time, deletedAt NullableTime) *ResponseListDatabase {
	this := ResponseListDatabase{}
	this.Id = id
	this.Name = name
	this.ClientId = clientId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.DeletedAt = deletedAt
	return &this
}

// NewResponseListDatabaseWithDefaults instantiates a new ResponseListDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseListDatabaseWithDefaults() *ResponseListDatabase {
	this := ResponseListDatabase{}
	return &this
}

// GetId returns the Id field value
func (o *ResponseListDatabase) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResponseListDatabase) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ResponseListDatabase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResponseListDatabase) SetName(v string) {
	o.Name = v
}

// GetClientId returns the ClientId field value
func (o *ResponseListDatabase) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *ResponseListDatabase) SetClientId(v string) {
	o.ClientId = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseListDatabase) GetStatus() StatusEnum {
	if o == nil || IsNil(o.Status) {
		var ret StatusEnum
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetStatusOk() (*StatusEnum, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseListDatabase) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given StatusEnum and assigns it to the Status field.
func (o *ResponseListDatabase) SetStatus(v StatusEnum) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ResponseListDatabase) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ResponseListDatabase) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ResponseListDatabase) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ResponseListDatabase) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ResponseListDatabase) GetDeletedAt() time.Time {
	if o == nil || o.DeletedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseListDatabase) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// SetDeletedAt sets field value
func (o *ResponseListDatabase) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ResponseListDatabase) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseListDatabase) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ResponseListDatabase) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ResponseListDatabase) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o ResponseListDatabase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseListDatabase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["client_id"] = o.ClientId
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["deleted_at"] = o.DeletedAt.Get()
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	return toSerialize, nil
}

func (o *ResponseListDatabase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"client_id",
		"created_at",
		"updated_at",
		"deleted_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseListDatabase := _ResponseListDatabase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseListDatabase)

	if err != nil {
		return err
	}

	*o = ResponseListDatabase(varResponseListDatabase)

	return err
}

type NullableResponseListDatabase struct {
	value *ResponseListDatabase
	isSet bool
}

func (v NullableResponseListDatabase) Get() *ResponseListDatabase {
	return v.value
}

func (v *NullableResponseListDatabase) Set(val *ResponseListDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseListDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseListDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseListDatabase(val *ResponseListDatabase) *NullableResponseListDatabase {
	return &NullableResponseListDatabase{value: val, isSet: true}
}

func (v NullableResponseListDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseListDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


