/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge/api/openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseRetrieveErrorResponses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseRetrieveErrorResponses{}

// ResponseRetrieveErrorResponses struct for ResponseRetrieveErrorResponses
type ResponseRetrieveErrorResponses struct {
	Data ErrorResponses `json:"data"`
}

type _ResponseRetrieveErrorResponses ResponseRetrieveErrorResponses

// NewResponseRetrieveErrorResponses instantiates a new ResponseRetrieveErrorResponses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseRetrieveErrorResponses(data ErrorResponses) *ResponseRetrieveErrorResponses {
	this := ResponseRetrieveErrorResponses{}
	this.Data = data
	return &this
}

// NewResponseRetrieveErrorResponsesWithDefaults instantiates a new ResponseRetrieveErrorResponses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseRetrieveErrorResponsesWithDefaults() *ResponseRetrieveErrorResponses {
	this := ResponseRetrieveErrorResponses{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseRetrieveErrorResponses) GetData() ErrorResponses {
	if o == nil {
		var ret ErrorResponses
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseRetrieveErrorResponses) GetDataOk() (*ErrorResponses, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseRetrieveErrorResponses) SetData(v ErrorResponses) {
	o.Data = v
}

func (o ResponseRetrieveErrorResponses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseRetrieveErrorResponses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResponseRetrieveErrorResponses) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseRetrieveErrorResponses := _ResponseRetrieveErrorResponses{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseRetrieveErrorResponses)

	if err != nil {
		return err
	}

	*o = ResponseRetrieveErrorResponses(varResponseRetrieveErrorResponses)

	return err
}

type NullableResponseRetrieveErrorResponses struct {
	value *ResponseRetrieveErrorResponses
	isSet bool
}

func (v NullableResponseRetrieveErrorResponses) Get() *ResponseRetrieveErrorResponses {
	return v.value
}

func (v *NullableResponseRetrieveErrorResponses) Set(val *ResponseRetrieveErrorResponses) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseRetrieveErrorResponses) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseRetrieveErrorResponses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseRetrieveErrorResponses(val *ResponseRetrieveErrorResponses) *NullableResponseRetrieveErrorResponses {
	return &NullableResponseRetrieveErrorResponses{value: val, isSet: true}
}

func (v NullableResponseRetrieveErrorResponses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseRetrieveErrorResponses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


