/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge/api/openapi

import (
	"encoding/json"
)

// checks if the ResponseBadRequestSerializerMetaclassModulesField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseBadRequestSerializerMetaclassModulesField{}

// ResponseBadRequestSerializerMetaclassModulesField struct for ResponseBadRequestSerializerMetaclassModulesField
type ResponseBadRequestSerializerMetaclassModulesField struct {
	EdgeCacheEnabled []string `json:"edge_cache_enabled,omitempty"`
	EdgeFunctionsEnabled []string `json:"edge_functions_enabled,omitempty"`
	ApplicationAcceleratorEnabled []string `json:"application_accelerator_enabled,omitempty"`
	ImageProcessorEnabled []string `json:"image_processor_enabled,omitempty"`
	TieredCacheEnabled []string `json:"tiered_cache_enabled,omitempty"`
}

// NewResponseBadRequestSerializerMetaclassModulesField instantiates a new ResponseBadRequestSerializerMetaclassModulesField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseBadRequestSerializerMetaclassModulesField() *ResponseBadRequestSerializerMetaclassModulesField {
	this := ResponseBadRequestSerializerMetaclassModulesField{}
	return &this
}

// NewResponseBadRequestSerializerMetaclassModulesFieldWithDefaults instantiates a new ResponseBadRequestSerializerMetaclassModulesField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseBadRequestSerializerMetaclassModulesFieldWithDefaults() *ResponseBadRequestSerializerMetaclassModulesField {
	this := ResponseBadRequestSerializerMetaclassModulesField{}
	return &this
}

// GetEdgeCacheEnabled returns the EdgeCacheEnabled field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetEdgeCacheEnabled() []string {
	if o == nil || IsNil(o.EdgeCacheEnabled) {
		var ret []string
		return ret
	}
	return o.EdgeCacheEnabled
}

// GetEdgeCacheEnabledOk returns a tuple with the EdgeCacheEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetEdgeCacheEnabledOk() ([]string, bool) {
	if o == nil || IsNil(o.EdgeCacheEnabled) {
		return nil, false
	}
	return o.EdgeCacheEnabled, true
}

// HasEdgeCacheEnabled returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) HasEdgeCacheEnabled() bool {
	if o != nil && !IsNil(o.EdgeCacheEnabled) {
		return true
	}

	return false
}

// SetEdgeCacheEnabled gets a reference to the given []string and assigns it to the EdgeCacheEnabled field.
func (o *ResponseBadRequestSerializerMetaclassModulesField) SetEdgeCacheEnabled(v []string) {
	o.EdgeCacheEnabled = v
}

// GetEdgeFunctionsEnabled returns the EdgeFunctionsEnabled field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetEdgeFunctionsEnabled() []string {
	if o == nil || IsNil(o.EdgeFunctionsEnabled) {
		var ret []string
		return ret
	}
	return o.EdgeFunctionsEnabled
}

// GetEdgeFunctionsEnabledOk returns a tuple with the EdgeFunctionsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetEdgeFunctionsEnabledOk() ([]string, bool) {
	if o == nil || IsNil(o.EdgeFunctionsEnabled) {
		return nil, false
	}
	return o.EdgeFunctionsEnabled, true
}

// HasEdgeFunctionsEnabled returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) HasEdgeFunctionsEnabled() bool {
	if o != nil && !IsNil(o.EdgeFunctionsEnabled) {
		return true
	}

	return false
}

// SetEdgeFunctionsEnabled gets a reference to the given []string and assigns it to the EdgeFunctionsEnabled field.
func (o *ResponseBadRequestSerializerMetaclassModulesField) SetEdgeFunctionsEnabled(v []string) {
	o.EdgeFunctionsEnabled = v
}

// GetApplicationAcceleratorEnabled returns the ApplicationAcceleratorEnabled field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetApplicationAcceleratorEnabled() []string {
	if o == nil || IsNil(o.ApplicationAcceleratorEnabled) {
		var ret []string
		return ret
	}
	return o.ApplicationAcceleratorEnabled
}

// GetApplicationAcceleratorEnabledOk returns a tuple with the ApplicationAcceleratorEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetApplicationAcceleratorEnabledOk() ([]string, bool) {
	if o == nil || IsNil(o.ApplicationAcceleratorEnabled) {
		return nil, false
	}
	return o.ApplicationAcceleratorEnabled, true
}

// HasApplicationAcceleratorEnabled returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) HasApplicationAcceleratorEnabled() bool {
	if o != nil && !IsNil(o.ApplicationAcceleratorEnabled) {
		return true
	}

	return false
}

// SetApplicationAcceleratorEnabled gets a reference to the given []string and assigns it to the ApplicationAcceleratorEnabled field.
func (o *ResponseBadRequestSerializerMetaclassModulesField) SetApplicationAcceleratorEnabled(v []string) {
	o.ApplicationAcceleratorEnabled = v
}

// GetImageProcessorEnabled returns the ImageProcessorEnabled field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetImageProcessorEnabled() []string {
	if o == nil || IsNil(o.ImageProcessorEnabled) {
		var ret []string
		return ret
	}
	return o.ImageProcessorEnabled
}

// GetImageProcessorEnabledOk returns a tuple with the ImageProcessorEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetImageProcessorEnabledOk() ([]string, bool) {
	if o == nil || IsNil(o.ImageProcessorEnabled) {
		return nil, false
	}
	return o.ImageProcessorEnabled, true
}

// HasImageProcessorEnabled returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) HasImageProcessorEnabled() bool {
	if o != nil && !IsNil(o.ImageProcessorEnabled) {
		return true
	}

	return false
}

// SetImageProcessorEnabled gets a reference to the given []string and assigns it to the ImageProcessorEnabled field.
func (o *ResponseBadRequestSerializerMetaclassModulesField) SetImageProcessorEnabled(v []string) {
	o.ImageProcessorEnabled = v
}

// GetTieredCacheEnabled returns the TieredCacheEnabled field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetTieredCacheEnabled() []string {
	if o == nil || IsNil(o.TieredCacheEnabled) {
		var ret []string
		return ret
	}
	return o.TieredCacheEnabled
}

// GetTieredCacheEnabledOk returns a tuple with the TieredCacheEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) GetTieredCacheEnabledOk() ([]string, bool) {
	if o == nil || IsNil(o.TieredCacheEnabled) {
		return nil, false
	}
	return o.TieredCacheEnabled, true
}

// HasTieredCacheEnabled returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassModulesField) HasTieredCacheEnabled() bool {
	if o != nil && !IsNil(o.TieredCacheEnabled) {
		return true
	}

	return false
}

// SetTieredCacheEnabled gets a reference to the given []string and assigns it to the TieredCacheEnabled field.
func (o *ResponseBadRequestSerializerMetaclassModulesField) SetTieredCacheEnabled(v []string) {
	o.TieredCacheEnabled = v
}

func (o ResponseBadRequestSerializerMetaclassModulesField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseBadRequestSerializerMetaclassModulesField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EdgeCacheEnabled) {
		toSerialize["edge_cache_enabled"] = o.EdgeCacheEnabled
	}
	if !IsNil(o.EdgeFunctionsEnabled) {
		toSerialize["edge_functions_enabled"] = o.EdgeFunctionsEnabled
	}
	if !IsNil(o.ApplicationAcceleratorEnabled) {
		toSerialize["application_accelerator_enabled"] = o.ApplicationAcceleratorEnabled
	}
	if !IsNil(o.ImageProcessorEnabled) {
		toSerialize["image_processor_enabled"] = o.ImageProcessorEnabled
	}
	if !IsNil(o.TieredCacheEnabled) {
		toSerialize["tiered_cache_enabled"] = o.TieredCacheEnabled
	}
	return toSerialize, nil
}

type NullableResponseBadRequestSerializerMetaclassModulesField struct {
	value *ResponseBadRequestSerializerMetaclassModulesField
	isSet bool
}

func (v NullableResponseBadRequestSerializerMetaclassModulesField) Get() *ResponseBadRequestSerializerMetaclassModulesField {
	return v.value
}

func (v *NullableResponseBadRequestSerializerMetaclassModulesField) Set(val *ResponseBadRequestSerializerMetaclassModulesField) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseBadRequestSerializerMetaclassModulesField) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseBadRequestSerializerMetaclassModulesField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseBadRequestSerializerMetaclassModulesField(val *ResponseBadRequestSerializerMetaclassModulesField) *NullableResponseBadRequestSerializerMetaclassModulesField {
	return &NullableResponseBadRequestSerializerMetaclassModulesField{value: val, isSet: true}
}

func (v NullableResponseBadRequestSerializerMetaclassModulesField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseBadRequestSerializerMetaclassModulesField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


