/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge/api/openapi

import (
	"encoding/json"
)

// checks if the PaginatedResponseListEdgeApplicationDeviceGroupsList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseListEdgeApplicationDeviceGroupsList{}

// PaginatedResponseListEdgeApplicationDeviceGroupsList struct for PaginatedResponseListEdgeApplicationDeviceGroupsList
type PaginatedResponseListEdgeApplicationDeviceGroupsList struct {
	Count *int64 `json:"count,omitempty"`
	Results []ResponseListEdgeApplicationDeviceGroups `json:"results,omitempty"`
}

// NewPaginatedResponseListEdgeApplicationDeviceGroupsList instantiates a new PaginatedResponseListEdgeApplicationDeviceGroupsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseListEdgeApplicationDeviceGroupsList() *PaginatedResponseListEdgeApplicationDeviceGroupsList {
	this := PaginatedResponseListEdgeApplicationDeviceGroupsList{}
	return &this
}

// NewPaginatedResponseListEdgeApplicationDeviceGroupsListWithDefaults instantiates a new PaginatedResponseListEdgeApplicationDeviceGroupsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseListEdgeApplicationDeviceGroupsListWithDefaults() *PaginatedResponseListEdgeApplicationDeviceGroupsList {
	this := PaginatedResponseListEdgeApplicationDeviceGroupsList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) GetResults() []ResponseListEdgeApplicationDeviceGroups {
	if o == nil || IsNil(o.Results) {
		var ret []ResponseListEdgeApplicationDeviceGroups
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) GetResultsOk() ([]ResponseListEdgeApplicationDeviceGroups, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ResponseListEdgeApplicationDeviceGroups and assigns it to the Results field.
func (o *PaginatedResponseListEdgeApplicationDeviceGroupsList) SetResults(v []ResponseListEdgeApplicationDeviceGroups) {
	o.Results = v
}

func (o PaginatedResponseListEdgeApplicationDeviceGroupsList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseListEdgeApplicationDeviceGroupsList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedResponseListEdgeApplicationDeviceGroupsList struct {
	value *PaginatedResponseListEdgeApplicationDeviceGroupsList
	isSet bool
}

func (v NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) Get() *PaginatedResponseListEdgeApplicationDeviceGroupsList {
	return v.value
}

func (v *NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) Set(val *PaginatedResponseListEdgeApplicationDeviceGroupsList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseListEdgeApplicationDeviceGroupsList(val *PaginatedResponseListEdgeApplicationDeviceGroupsList) *NullablePaginatedResponseListEdgeApplicationDeviceGroupsList {
	return &NullablePaginatedResponseListEdgeApplicationDeviceGroupsList{value: val, isSet: true}
}

func (v NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseListEdgeApplicationDeviceGroupsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


