/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge/api/openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseDeleteWAFRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteWAFRule{}

// ResponseDeleteWAFRule struct for ResponseDeleteWAFRule
type ResponseDeleteWAFRule struct {
	// * `pending` - pending * `executed` - executed
	State string `json:"state"`
	Data NullableWAFRule `json:"data"`
}

type _ResponseDeleteWAFRule ResponseDeleteWAFRule

// NewResponseDeleteWAFRule instantiates a new ResponseDeleteWAFRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteWAFRule(state string, data NullableWAFRule) *ResponseDeleteWAFRule {
	this := ResponseDeleteWAFRule{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseDeleteWAFRuleWithDefaults instantiates a new ResponseDeleteWAFRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteWAFRuleWithDefaults() *ResponseDeleteWAFRule {
	this := ResponseDeleteWAFRule{}
	return &this
}

// GetState returns the State field value
func (o *ResponseDeleteWAFRule) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseDeleteWAFRule) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseDeleteWAFRule) SetState(v string) {
	o.State = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for WAFRule will be returned
func (o *ResponseDeleteWAFRule) GetData() WAFRule {
	if o == nil || o.Data.Get() == nil {
		var ret WAFRule
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseDeleteWAFRule) GetDataOk() (*WAFRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *ResponseDeleteWAFRule) SetData(v WAFRule) {
	o.Data.Set(&v)
}

func (o ResponseDeleteWAFRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteWAFRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data.Get()
	return toSerialize, nil
}

func (o *ResponseDeleteWAFRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseDeleteWAFRule := _ResponseDeleteWAFRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseDeleteWAFRule)

	if err != nil {
		return err
	}

	*o = ResponseDeleteWAFRule(varResponseDeleteWAFRule)

	return err
}

type NullableResponseDeleteWAFRule struct {
	value *ResponseDeleteWAFRule
	isSet bool
}

func (v NullableResponseDeleteWAFRule) Get() *ResponseDeleteWAFRule {
	return v.value
}

func (v *NullableResponseDeleteWAFRule) Set(val *ResponseDeleteWAFRule) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteWAFRule) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteWAFRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteWAFRule(val *ResponseDeleteWAFRule) *NullableResponseDeleteWAFRule {
	return &NullableResponseDeleteWAFRule{value: val, isSet: true}
}

func (v NullableResponseDeleteWAFRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteWAFRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


