/*
Accounts API

REST API OpenAPI documentation for the Accounts API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounts

import (
	"encoding/json"
)

// checks if the CurrencyIsoCodeEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrencyIsoCodeEnum{}

// CurrencyIsoCodeEnum * `USD` - USD * `BRL` - BRL
type CurrencyIsoCodeEnum struct {
}

// NewCurrencyIsoCodeEnum instantiates a new CurrencyIsoCodeEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrencyIsoCodeEnum() *CurrencyIsoCodeEnum {
	this := CurrencyIsoCodeEnum{}
	return &this
}

// NewCurrencyIsoCodeEnumWithDefaults instantiates a new CurrencyIsoCodeEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrencyIsoCodeEnumWithDefaults() *CurrencyIsoCodeEnum {
	this := CurrencyIsoCodeEnum{}
	return &this
}

func (o CurrencyIsoCodeEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrencyIsoCodeEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableCurrencyIsoCodeEnum struct {
	value CurrencyIsoCodeEnum
	isSet bool
}

func (v NullableCurrencyIsoCodeEnum) Get() CurrencyIsoCodeEnum {
	return v.value
}

func (v *NullableCurrencyIsoCodeEnum) Set(val CurrencyIsoCodeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrencyIsoCodeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrencyIsoCodeEnum) Unset() {
	v.isSet = false
}

func NewNullableCurrencyIsoCodeEnum(val CurrencyIsoCodeEnum) *NullableCurrencyIsoCodeEnum {
	return &NullableCurrencyIsoCodeEnum{value: val, isSet: true}
}

func (v NullableCurrencyIsoCodeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrencyIsoCodeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


