/*
Accounts API

REST API OpenAPI documentation for the Accounts API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounts-api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseDeleteAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteAccount{}

// ResponseDeleteAccount struct for ResponseDeleteAccount
type ResponseDeleteAccount struct {
	State StateEnum `json:"state"`
	Data NullableAccount `json:"data"`
}

type _ResponseDeleteAccount ResponseDeleteAccount

// NewResponseDeleteAccount instantiates a new ResponseDeleteAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteAccount(state StateEnum, data NullableAccount) *ResponseDeleteAccount {
	this := ResponseDeleteAccount{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseDeleteAccountWithDefaults instantiates a new ResponseDeleteAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteAccountWithDefaults() *ResponseDeleteAccount {
	this := ResponseDeleteAccount{}
	return &this
}

// GetState returns the State field value
func (o *ResponseDeleteAccount) GetState() StateEnum {
	if o == nil {
		var ret StateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseDeleteAccount) GetStateOk() (*StateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseDeleteAccount) SetState(v StateEnum) {
	o.State = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for Account will be returned
func (o *ResponseDeleteAccount) GetData() Account {
	if o == nil || o.Data.Get() == nil {
		var ret Account
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseDeleteAccount) GetDataOk() (*Account, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *ResponseDeleteAccount) SetData(v Account) {
	o.Data.Set(&v)
}

func (o ResponseDeleteAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data.Get()
	return toSerialize, nil
}

func (o *ResponseDeleteAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseDeleteAccount := _ResponseDeleteAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseDeleteAccount)

	if err != nil {
		return err
	}

	*o = ResponseDeleteAccount(varResponseDeleteAccount)

	return err
}

type NullableResponseDeleteAccount struct {
	value *ResponseDeleteAccount
	isSet bool
}

func (v NullableResponseDeleteAccount) Get() *ResponseDeleteAccount {
	return v.value
}

func (v *NullableResponseDeleteAccount) Set(val *ResponseDeleteAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteAccount(val *ResponseDeleteAccount) *NullableResponseDeleteAccount {
	return &NullableResponseDeleteAccount{value: val, isSet: true}
}

func (v NullableResponseDeleteAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


