/*
data-stream-api

REST API OpenAPI documentation for the Data Stream

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package data-stream-api

import (
	"encoding/json"
)

// checks if the DataStreamFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStreamFilter{}

// DataStreamFilter struct for DataStreamFilter
type DataStreamFilter struct {
	SamplingEnable *bool `json:"sampling_enable,omitempty"`
	SamplingRate *int64 `json:"sampling_rate,omitempty"`
	Workloads []int64 `json:"workloads,omitempty"`
}

// NewDataStreamFilter instantiates a new DataStreamFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStreamFilter() *DataStreamFilter {
	this := DataStreamFilter{}
	return &this
}

// NewDataStreamFilterWithDefaults instantiates a new DataStreamFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStreamFilterWithDefaults() *DataStreamFilter {
	this := DataStreamFilter{}
	return &this
}

// GetSamplingEnable returns the SamplingEnable field value if set, zero value otherwise.
func (o *DataStreamFilter) GetSamplingEnable() bool {
	if o == nil || IsNil(o.SamplingEnable) {
		var ret bool
		return ret
	}
	return *o.SamplingEnable
}

// GetSamplingEnableOk returns a tuple with the SamplingEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStreamFilter) GetSamplingEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.SamplingEnable) {
		return nil, false
	}
	return o.SamplingEnable, true
}

// HasSamplingEnable returns a boolean if a field has been set.
func (o *DataStreamFilter) HasSamplingEnable() bool {
	if o != nil && !IsNil(o.SamplingEnable) {
		return true
	}

	return false
}

// SetSamplingEnable gets a reference to the given bool and assigns it to the SamplingEnable field.
func (o *DataStreamFilter) SetSamplingEnable(v bool) {
	o.SamplingEnable = &v
}

// GetSamplingRate returns the SamplingRate field value if set, zero value otherwise.
func (o *DataStreamFilter) GetSamplingRate() int64 {
	if o == nil || IsNil(o.SamplingRate) {
		var ret int64
		return ret
	}
	return *o.SamplingRate
}

// GetSamplingRateOk returns a tuple with the SamplingRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStreamFilter) GetSamplingRateOk() (*int64, bool) {
	if o == nil || IsNil(o.SamplingRate) {
		return nil, false
	}
	return o.SamplingRate, true
}

// HasSamplingRate returns a boolean if a field has been set.
func (o *DataStreamFilter) HasSamplingRate() bool {
	if o != nil && !IsNil(o.SamplingRate) {
		return true
	}

	return false
}

// SetSamplingRate gets a reference to the given int64 and assigns it to the SamplingRate field.
func (o *DataStreamFilter) SetSamplingRate(v int64) {
	o.SamplingRate = &v
}

// GetWorkloads returns the Workloads field value if set, zero value otherwise.
func (o *DataStreamFilter) GetWorkloads() []int64 {
	if o == nil || IsNil(o.Workloads) {
		var ret []int64
		return ret
	}
	return o.Workloads
}

// GetWorkloadsOk returns a tuple with the Workloads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStreamFilter) GetWorkloadsOk() ([]int64, bool) {
	if o == nil || IsNil(o.Workloads) {
		return nil, false
	}
	return o.Workloads, true
}

// HasWorkloads returns a boolean if a field has been set.
func (o *DataStreamFilter) HasWorkloads() bool {
	if o != nil && !IsNil(o.Workloads) {
		return true
	}

	return false
}

// SetWorkloads gets a reference to the given []int64 and assigns it to the Workloads field.
func (o *DataStreamFilter) SetWorkloads(v []int64) {
	o.Workloads = v
}

func (o DataStreamFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStreamFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SamplingEnable) {
		toSerialize["sampling_enable"] = o.SamplingEnable
	}
	if !IsNil(o.SamplingRate) {
		toSerialize["sampling_rate"] = o.SamplingRate
	}
	if !IsNil(o.Workloads) {
		toSerialize["workloads"] = o.Workloads
	}
	return toSerialize, nil
}

type NullableDataStreamFilter struct {
	value *DataStreamFilter
	isSet bool
}

func (v NullableDataStreamFilter) Get() *DataStreamFilter {
	return v.value
}

func (v *NullableDataStreamFilter) Set(val *DataStreamFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStreamFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStreamFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStreamFilter(val *DataStreamFilter) *NullableDataStreamFilter {
	return &NullableDataStreamFilter{value: val, isSet: true}
}

func (v NullableDataStreamFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStreamFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


