/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the PhaseEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhaseEnum{}

// PhaseEnum * `default` - default * `request` - request * `response` - response
type PhaseEnum struct {
}

// NewPhaseEnum instantiates a new PhaseEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhaseEnum() *PhaseEnum {
	this := PhaseEnum{}
	return &this
}

// NewPhaseEnumWithDefaults instantiates a new PhaseEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhaseEnumWithDefaults() *PhaseEnum {
	this := PhaseEnum{}
	return &this
}

func (o PhaseEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhaseEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullablePhaseEnum struct {
	value PhaseEnum
	isSet bool
}

func (v NullablePhaseEnum) Get() PhaseEnum {
	return v.value
}

func (v *NullablePhaseEnum) Set(val PhaseEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePhaseEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePhaseEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhaseEnum(val PhaseEnum) *NullablePhaseEnum {
	return &NullablePhaseEnum{value: val, isSet: true}
}

func (v NullablePhaseEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhaseEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


