/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// MatchZoneMatchesOn - struct for MatchZoneMatchesOn
type MatchZoneMatchesOn struct {
	BlankEnum *BlankEnum
	MatchesOnEnum *MatchesOnEnum
}

// BlankEnumAsMatchZoneMatchesOn is a convenience function that returns BlankEnum wrapped in MatchZoneMatchesOn
func BlankEnumAsMatchZoneMatchesOn(v *BlankEnum) MatchZoneMatchesOn {
	return MatchZoneMatchesOn{
		BlankEnum: v,
	}
}

// MatchesOnEnumAsMatchZoneMatchesOn is a convenience function that returns MatchesOnEnum wrapped in MatchZoneMatchesOn
func MatchesOnEnumAsMatchZoneMatchesOn(v *MatchesOnEnum) MatchZoneMatchesOn {
	return MatchZoneMatchesOn{
		MatchesOnEnum: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MatchZoneMatchesOn) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BlankEnum
	err = newStrictDecoder(data).Decode(&dst.BlankEnum)
	if err == nil {
		jsonBlankEnum, _ := json.Marshal(dst.BlankEnum)
		if string(jsonBlankEnum) == "{}" { // empty struct
			dst.BlankEnum = nil
		} else {
			if err = validator.Validate(dst.BlankEnum); err != nil {
				dst.BlankEnum = nil
			} else {
				match++
			}
		}
	} else {
		dst.BlankEnum = nil
	}

	// try to unmarshal data into MatchesOnEnum
	err = newStrictDecoder(data).Decode(&dst.MatchesOnEnum)
	if err == nil {
		jsonMatchesOnEnum, _ := json.Marshal(dst.MatchesOnEnum)
		if string(jsonMatchesOnEnum) == "{}" { // empty struct
			dst.MatchesOnEnum = nil
		} else {
			if err = validator.Validate(dst.MatchesOnEnum); err != nil {
				dst.MatchesOnEnum = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesOnEnum = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BlankEnum = nil
		dst.MatchesOnEnum = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MatchZoneMatchesOn)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MatchZoneMatchesOn)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MatchZoneMatchesOn) MarshalJSON() ([]byte, error) {
	if src.BlankEnum != nil {
		return json.Marshal(&src.BlankEnum)
	}

	if src.MatchesOnEnum != nil {
		return json.Marshal(&src.MatchesOnEnum)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MatchZoneMatchesOn) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BlankEnum != nil {
		return obj.BlankEnum
	}

	if obj.MatchesOnEnum != nil {
		return obj.MatchesOnEnum
	}

	// all schemas are nil
	return nil
}

type NullableMatchZoneMatchesOn struct {
	value *MatchZoneMatchesOn
	isSet bool
}

func (v NullableMatchZoneMatchesOn) Get() *MatchZoneMatchesOn {
	return v.value
}

func (v *NullableMatchZoneMatchesOn) Set(val *MatchZoneMatchesOn) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchZoneMatchesOn) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchZoneMatchesOn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchZoneMatchesOn(val *MatchZoneMatchesOn) *NullableMatchZoneMatchesOn {
	return &NullableMatchZoneMatchesOn{value: val, isSet: true}
}

func (v NullableMatchZoneMatchesOn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchZoneMatchesOn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


