/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the ResponseBadRequestSerializerMetaclassConnectorCustomPagesField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseBadRequestSerializerMetaclassConnectorCustomPagesField{}

// ResponseBadRequestSerializerMetaclassConnectorCustomPagesField struct for ResponseBadRequestSerializerMetaclassConnectorCustomPagesField
type ResponseBadRequestSerializerMetaclassConnectorCustomPagesField struct {
	Pages *ResponseBadRequestBaseEdgeConnectorConnectionPreference `json:"pages,omitempty"`
}

// NewResponseBadRequestSerializerMetaclassConnectorCustomPagesField instantiates a new ResponseBadRequestSerializerMetaclassConnectorCustomPagesField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseBadRequestSerializerMetaclassConnectorCustomPagesField() *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField {
	this := ResponseBadRequestSerializerMetaclassConnectorCustomPagesField{}
	return &this
}

// NewResponseBadRequestSerializerMetaclassConnectorCustomPagesFieldWithDefaults instantiates a new ResponseBadRequestSerializerMetaclassConnectorCustomPagesField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseBadRequestSerializerMetaclassConnectorCustomPagesFieldWithDefaults() *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField {
	this := ResponseBadRequestSerializerMetaclassConnectorCustomPagesField{}
	return &this
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) GetPages() ResponseBadRequestBaseEdgeConnectorConnectionPreference {
	if o == nil || IsNil(o.Pages) {
		var ret ResponseBadRequestBaseEdgeConnectorConnectionPreference
		return ret
	}
	return *o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) GetPagesOk() (*ResponseBadRequestBaseEdgeConnectorConnectionPreference, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given ResponseBadRequestBaseEdgeConnectorConnectionPreference and assigns it to the Pages field.
func (o *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) SetPages(v ResponseBadRequestBaseEdgeConnectorConnectionPreference) {
	o.Pages = &v
}

func (o ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}
	return toSerialize, nil
}

type NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField struct {
	value *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField
	isSet bool
}

func (v NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) Get() *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField {
	return v.value
}

func (v *NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) Set(val *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField(val *ResponseBadRequestSerializerMetaclassConnectorCustomPagesField) *NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField {
	return &NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField{value: val, isSet: true}
}

func (v NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseBadRequestSerializerMetaclassConnectorCustomPagesField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


