/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the CrossSiteScriptingSensitivityEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrossSiteScriptingSensitivityEnum{}

// CrossSiteScriptingSensitivityEnum * `lowest` - lowest * `low` - low * `medium` - medium * `high` - high * `highest` - highest
type CrossSiteScriptingSensitivityEnum struct {
}

// NewCrossSiteScriptingSensitivityEnum instantiates a new CrossSiteScriptingSensitivityEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrossSiteScriptingSensitivityEnum() *CrossSiteScriptingSensitivityEnum {
	this := CrossSiteScriptingSensitivityEnum{}
	return &this
}

// NewCrossSiteScriptingSensitivityEnumWithDefaults instantiates a new CrossSiteScriptingSensitivityEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrossSiteScriptingSensitivityEnumWithDefaults() *CrossSiteScriptingSensitivityEnum {
	this := CrossSiteScriptingSensitivityEnum{}
	return &this
}

func (o CrossSiteScriptingSensitivityEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrossSiteScriptingSensitivityEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableCrossSiteScriptingSensitivityEnum struct {
	value CrossSiteScriptingSensitivityEnum
	isSet bool
}

func (v NullableCrossSiteScriptingSensitivityEnum) Get() CrossSiteScriptingSensitivityEnum {
	return v.value
}

func (v *NullableCrossSiteScriptingSensitivityEnum) Set(val CrossSiteScriptingSensitivityEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCrossSiteScriptingSensitivityEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCrossSiteScriptingSensitivityEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrossSiteScriptingSensitivityEnum(val CrossSiteScriptingSensitivityEnum) *NullableCrossSiteScriptingSensitivityEnum {
	return &NullableCrossSiteScriptingSensitivityEnum{value: val, isSet: true}
}

func (v NullableCrossSiteScriptingSensitivityEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrossSiteScriptingSensitivityEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


