/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the CacheByCookiesEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheByCookiesEnum{}

// CacheByCookiesEnum * `ignore` - Content does not vary by Cookies (Improves Caching) * `whitelist` - Content varies by some Cookies (Whitelist) * `blacklist` - Content varies by Cookies, with the exception of a few (Blacklist) * `all` - Content varies by all Cookies
type CacheByCookiesEnum struct {
}

// NewCacheByCookiesEnum instantiates a new CacheByCookiesEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheByCookiesEnum() *CacheByCookiesEnum {
	this := CacheByCookiesEnum{}
	return &this
}

// NewCacheByCookiesEnumWithDefaults instantiates a new CacheByCookiesEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheByCookiesEnumWithDefaults() *CacheByCookiesEnum {
	this := CacheByCookiesEnum{}
	return &this
}

func (o CacheByCookiesEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheByCookiesEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableCacheByCookiesEnum struct {
	value CacheByCookiesEnum
	isSet bool
}

func (v NullableCacheByCookiesEnum) Get() CacheByCookiesEnum {
	return v.value
}

func (v *NullableCacheByCookiesEnum) Set(val CacheByCookiesEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheByCookiesEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheByCookiesEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheByCookiesEnum(val CacheByCookiesEnum) *NullableCacheByCookiesEnum {
	return &NullableCacheByCookiesEnum{value: val, isSet: true}
}

func (v NullableCacheByCookiesEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheByCookiesEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


