/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkloadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkloadRequest{}

// WorkloadRequest struct for WorkloadRequest
type WorkloadRequest struct {
	Name string `json:"name" validate:"regexp=.*"`
	AlternateDomains []string `json:"alternate_domains,omitempty"`
	EdgeApplication int64 `json:"edge_application"`
	Active *bool `json:"active,omitempty"`
	NetworkMap *NetworkMapEnum `json:"network_map,omitempty"`
	EdgeFirewall NullableInt32 `json:"edge_firewall,omitempty"`
	Tls *TLSRequest `json:"tls,omitempty"`
	Protocols *ProtocolsRequest `json:"protocols,omitempty"`
	Mtls *MTLSRequest `json:"mtls,omitempty"`
	Domains []DomainInfoRequest `json:"domains,omitempty"`
}

type _WorkloadRequest WorkloadRequest

// NewWorkloadRequest instantiates a new WorkloadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadRequest(name string, edgeApplication int64) *WorkloadRequest {
	this := WorkloadRequest{}
	this.Name = name
	this.EdgeApplication = edgeApplication
	var active bool = true
	this.Active = &active
	var networkMap NetworkMapEnum = 1
	this.NetworkMap = &networkMap
	var tls TLSRequest = {"certificate":null,"ciphers":null,"minimum_version":"tls_1_2"}
	this.Tls = &tls
	var protocols ProtocolsRequest = {"http":{"versions":["http1","http2"],"http_ports":[80],"https_ports":[443],"quic_ports":null}}
	this.Protocols = &protocols
	return &this
}

// NewWorkloadRequestWithDefaults instantiates a new WorkloadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadRequestWithDefaults() *WorkloadRequest {
	this := WorkloadRequest{}
	var active bool = true
	this.Active = &active
	var networkMap NetworkMapEnum = 1
	this.NetworkMap = &networkMap
	var tls TLSRequest = {"certificate":null,"ciphers":null,"minimum_version":"tls_1_2"}
	this.Tls = &tls
	var protocols ProtocolsRequest = {"http":{"versions":["http1","http2"],"http_ports":[80],"https_ports":[443],"quic_ports":null}}
	this.Protocols = &protocols
	return &this
}

// GetName returns the Name field value
func (o *WorkloadRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkloadRequest) SetName(v string) {
	o.Name = v
}

// GetAlternateDomains returns the AlternateDomains field value if set, zero value otherwise.
func (o *WorkloadRequest) GetAlternateDomains() []string {
	if o == nil || IsNil(o.AlternateDomains) {
		var ret []string
		return ret
	}
	return o.AlternateDomains
}

// GetAlternateDomainsOk returns a tuple with the AlternateDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetAlternateDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.AlternateDomains) {
		return nil, false
	}
	return o.AlternateDomains, true
}

// HasAlternateDomains returns a boolean if a field has been set.
func (o *WorkloadRequest) HasAlternateDomains() bool {
	if o != nil && !IsNil(o.AlternateDomains) {
		return true
	}

	return false
}

// SetAlternateDomains gets a reference to the given []string and assigns it to the AlternateDomains field.
func (o *WorkloadRequest) SetAlternateDomains(v []string) {
	o.AlternateDomains = v
}

// GetEdgeApplication returns the EdgeApplication field value
func (o *WorkloadRequest) GetEdgeApplication() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EdgeApplication
}

// GetEdgeApplicationOk returns a tuple with the EdgeApplication field value
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetEdgeApplicationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EdgeApplication, true
}

// SetEdgeApplication sets field value
func (o *WorkloadRequest) SetEdgeApplication(v int64) {
	o.EdgeApplication = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *WorkloadRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *WorkloadRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *WorkloadRequest) SetActive(v bool) {
	o.Active = &v
}

// GetNetworkMap returns the NetworkMap field value if set, zero value otherwise.
func (o *WorkloadRequest) GetNetworkMap() NetworkMapEnum {
	if o == nil || IsNil(o.NetworkMap) {
		var ret NetworkMapEnum
		return ret
	}
	return *o.NetworkMap
}

// GetNetworkMapOk returns a tuple with the NetworkMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetNetworkMapOk() (*NetworkMapEnum, bool) {
	if o == nil || IsNil(o.NetworkMap) {
		return nil, false
	}
	return o.NetworkMap, true
}

// HasNetworkMap returns a boolean if a field has been set.
func (o *WorkloadRequest) HasNetworkMap() bool {
	if o != nil && !IsNil(o.NetworkMap) {
		return true
	}

	return false
}

// SetNetworkMap gets a reference to the given NetworkMapEnum and assigns it to the NetworkMap field.
func (o *WorkloadRequest) SetNetworkMap(v NetworkMapEnum) {
	o.NetworkMap = &v
}

// GetEdgeFirewall returns the EdgeFirewall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkloadRequest) GetEdgeFirewall() int32 {
	if o == nil || IsNil(o.EdgeFirewall.Get()) {
		var ret int32
		return ret
	}
	return *o.EdgeFirewall.Get()
}

// GetEdgeFirewallOk returns a tuple with the EdgeFirewall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkloadRequest) GetEdgeFirewallOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EdgeFirewall.Get(), o.EdgeFirewall.IsSet()
}

// HasEdgeFirewall returns a boolean if a field has been set.
func (o *WorkloadRequest) HasEdgeFirewall() bool {
	if o != nil && o.EdgeFirewall.IsSet() {
		return true
	}

	return false
}

// SetEdgeFirewall gets a reference to the given NullableInt32 and assigns it to the EdgeFirewall field.
func (o *WorkloadRequest) SetEdgeFirewall(v int32) {
	o.EdgeFirewall.Set(&v)
}
// SetEdgeFirewallNil sets the value for EdgeFirewall to be an explicit nil
func (o *WorkloadRequest) SetEdgeFirewallNil() {
	o.EdgeFirewall.Set(nil)
}

// UnsetEdgeFirewall ensures that no value is present for EdgeFirewall, not even an explicit nil
func (o *WorkloadRequest) UnsetEdgeFirewall() {
	o.EdgeFirewall.Unset()
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *WorkloadRequest) GetTls() TLSRequest {
	if o == nil || IsNil(o.Tls) {
		var ret TLSRequest
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetTlsOk() (*TLSRequest, bool) {
	if o == nil || IsNil(o.Tls) {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *WorkloadRequest) HasTls() bool {
	if o != nil && !IsNil(o.Tls) {
		return true
	}

	return false
}

// SetTls gets a reference to the given TLSRequest and assigns it to the Tls field.
func (o *WorkloadRequest) SetTls(v TLSRequest) {
	o.Tls = &v
}

// GetProtocols returns the Protocols field value if set, zero value otherwise.
func (o *WorkloadRequest) GetProtocols() ProtocolsRequest {
	if o == nil || IsNil(o.Protocols) {
		var ret ProtocolsRequest
		return ret
	}
	return *o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetProtocolsOk() (*ProtocolsRequest, bool) {
	if o == nil || IsNil(o.Protocols) {
		return nil, false
	}
	return o.Protocols, true
}

// HasProtocols returns a boolean if a field has been set.
func (o *WorkloadRequest) HasProtocols() bool {
	if o != nil && !IsNil(o.Protocols) {
		return true
	}

	return false
}

// SetProtocols gets a reference to the given ProtocolsRequest and assigns it to the Protocols field.
func (o *WorkloadRequest) SetProtocols(v ProtocolsRequest) {
	o.Protocols = &v
}

// GetMtls returns the Mtls field value if set, zero value otherwise.
func (o *WorkloadRequest) GetMtls() MTLSRequest {
	if o == nil || IsNil(o.Mtls) {
		var ret MTLSRequest
		return ret
	}
	return *o.Mtls
}

// GetMtlsOk returns a tuple with the Mtls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetMtlsOk() (*MTLSRequest, bool) {
	if o == nil || IsNil(o.Mtls) {
		return nil, false
	}
	return o.Mtls, true
}

// HasMtls returns a boolean if a field has been set.
func (o *WorkloadRequest) HasMtls() bool {
	if o != nil && !IsNil(o.Mtls) {
		return true
	}

	return false
}

// SetMtls gets a reference to the given MTLSRequest and assigns it to the Mtls field.
func (o *WorkloadRequest) SetMtls(v MTLSRequest) {
	o.Mtls = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *WorkloadRequest) GetDomains() []DomainInfoRequest {
	if o == nil || IsNil(o.Domains) {
		var ret []DomainInfoRequest
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRequest) GetDomainsOk() ([]DomainInfoRequest, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *WorkloadRequest) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []DomainInfoRequest and assigns it to the Domains field.
func (o *WorkloadRequest) SetDomains(v []DomainInfoRequest) {
	o.Domains = v
}

func (o WorkloadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkloadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.AlternateDomains) {
		toSerialize["alternate_domains"] = o.AlternateDomains
	}
	toSerialize["edge_application"] = o.EdgeApplication
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.NetworkMap) {
		toSerialize["network_map"] = o.NetworkMap
	}
	if o.EdgeFirewall.IsSet() {
		toSerialize["edge_firewall"] = o.EdgeFirewall.Get()
	}
	if !IsNil(o.Tls) {
		toSerialize["tls"] = o.Tls
	}
	if !IsNil(o.Protocols) {
		toSerialize["protocols"] = o.Protocols
	}
	if !IsNil(o.Mtls) {
		toSerialize["mtls"] = o.Mtls
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	return toSerialize, nil
}

func (o *WorkloadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"edge_application",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkloadRequest := _WorkloadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkloadRequest)

	if err != nil {
		return err
	}

	*o = WorkloadRequest(varWorkloadRequest)

	return err
}

type NullableWorkloadRequest struct {
	value *WorkloadRequest
	isSet bool
}

func (v NullableWorkloadRequest) Get() *WorkloadRequest {
	return v.value
}

func (v *NullableWorkloadRequest) Set(val *WorkloadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadRequest(val *WorkloadRequest) *NullableWorkloadRequest {
	return &NullableWorkloadRequest{value: val, isSet: true}
}

func (v NullableWorkloadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


