/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the LanguageEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LanguageEnum{}

// LanguageEnum * `javascript` - JavaScript * `lua` - Lua
type LanguageEnum struct {
}

// NewLanguageEnum instantiates a new LanguageEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanguageEnum() *LanguageEnum {
	this := LanguageEnum{}
	return &this
}

// NewLanguageEnumWithDefaults instantiates a new LanguageEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanguageEnumWithDefaults() *LanguageEnum {
	this := LanguageEnum{}
	return &this
}

func (o LanguageEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LanguageEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableLanguageEnum struct {
	value LanguageEnum
	isSet bool
}

func (v NullableLanguageEnum) Get() LanguageEnum {
	return v.value
}

func (v *NullableLanguageEnum) Set(val LanguageEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLanguageEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLanguageEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanguageEnum(val LanguageEnum) *NullableLanguageEnum {
	return &NullableLanguageEnum{value: val, isSet: true}
}

func (v NullableLanguageEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanguageEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


