/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseDeleteEdgeApplication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteEdgeApplication{}

// ResponseDeleteEdgeApplication struct for ResponseDeleteEdgeApplication
type ResponseDeleteEdgeApplication struct {
	State StateEnum `json:"state"`
	Data NullableEdgeApplication `json:"data"`
}

type _ResponseDeleteEdgeApplication ResponseDeleteEdgeApplication

// NewResponseDeleteEdgeApplication instantiates a new ResponseDeleteEdgeApplication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteEdgeApplication(state StateEnum, data NullableEdgeApplication) *ResponseDeleteEdgeApplication {
	this := ResponseDeleteEdgeApplication{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseDeleteEdgeApplicationWithDefaults instantiates a new ResponseDeleteEdgeApplication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteEdgeApplicationWithDefaults() *ResponseDeleteEdgeApplication {
	this := ResponseDeleteEdgeApplication{}
	return &this
}

// GetState returns the State field value
func (o *ResponseDeleteEdgeApplication) GetState() StateEnum {
	if o == nil {
		var ret StateEnum
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseDeleteEdgeApplication) GetStateOk() (*StateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseDeleteEdgeApplication) SetState(v StateEnum) {
	o.State = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for EdgeApplication will be returned
func (o *ResponseDeleteEdgeApplication) GetData() EdgeApplication {
	if o == nil || o.Data.Get() == nil {
		var ret EdgeApplication
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseDeleteEdgeApplication) GetDataOk() (*EdgeApplication, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *ResponseDeleteEdgeApplication) SetData(v EdgeApplication) {
	o.Data.Set(&v)
}

func (o ResponseDeleteEdgeApplication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteEdgeApplication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data.Get()
	return toSerialize, nil
}

func (o *ResponseDeleteEdgeApplication) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseDeleteEdgeApplication := _ResponseDeleteEdgeApplication{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseDeleteEdgeApplication)

	if err != nil {
		return err
	}

	*o = ResponseDeleteEdgeApplication(varResponseDeleteEdgeApplication)

	return err
}

type NullableResponseDeleteEdgeApplication struct {
	value *ResponseDeleteEdgeApplication
	isSet bool
}

func (v NullableResponseDeleteEdgeApplication) Get() *ResponseDeleteEdgeApplication {
	return v.value
}

func (v *NullableResponseDeleteEdgeApplication) Set(val *ResponseDeleteEdgeApplication) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteEdgeApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteEdgeApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteEdgeApplication(val *ResponseDeleteEdgeApplication) *NullableResponseDeleteEdgeApplication {
	return &NullableResponseDeleteEdgeApplication{value: val, isSet: true}
}

func (v NullableResponseDeleteEdgeApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteEdgeApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


