/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the PaginatedResponseListBaseEdgeConnectorList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseListBaseEdgeConnectorList{}

// PaginatedResponseListBaseEdgeConnectorList struct for PaginatedResponseListBaseEdgeConnectorList
type PaginatedResponseListBaseEdgeConnectorList struct {
	Count *int64 `json:"count,omitempty"`
	Results []ResponseListBaseEdgeConnector `json:"results,omitempty"`
}

// NewPaginatedResponseListBaseEdgeConnectorList instantiates a new PaginatedResponseListBaseEdgeConnectorList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseListBaseEdgeConnectorList() *PaginatedResponseListBaseEdgeConnectorList {
	this := PaginatedResponseListBaseEdgeConnectorList{}
	return &this
}

// NewPaginatedResponseListBaseEdgeConnectorListWithDefaults instantiates a new PaginatedResponseListBaseEdgeConnectorList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseListBaseEdgeConnectorListWithDefaults() *PaginatedResponseListBaseEdgeConnectorList {
	this := PaginatedResponseListBaseEdgeConnectorList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedResponseListBaseEdgeConnectorList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListBaseEdgeConnectorList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedResponseListBaseEdgeConnectorList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *PaginatedResponseListBaseEdgeConnectorList) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedResponseListBaseEdgeConnectorList) GetResults() []ResponseListBaseEdgeConnector {
	if o == nil || IsNil(o.Results) {
		var ret []ResponseListBaseEdgeConnector
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListBaseEdgeConnectorList) GetResultsOk() ([]ResponseListBaseEdgeConnector, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedResponseListBaseEdgeConnectorList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ResponseListBaseEdgeConnector and assigns it to the Results field.
func (o *PaginatedResponseListBaseEdgeConnectorList) SetResults(v []ResponseListBaseEdgeConnector) {
	o.Results = v
}

func (o PaginatedResponseListBaseEdgeConnectorList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseListBaseEdgeConnectorList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedResponseListBaseEdgeConnectorList struct {
	value *PaginatedResponseListBaseEdgeConnectorList
	isSet bool
}

func (v NullablePaginatedResponseListBaseEdgeConnectorList) Get() *PaginatedResponseListBaseEdgeConnectorList {
	return v.value
}

func (v *NullablePaginatedResponseListBaseEdgeConnectorList) Set(val *PaginatedResponseListBaseEdgeConnectorList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseListBaseEdgeConnectorList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseListBaseEdgeConnectorList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseListBaseEdgeConnectorList(val *PaginatedResponseListBaseEdgeConnectorList) *NullablePaginatedResponseListBaseEdgeConnectorList {
	return &NullablePaginatedResponseListBaseEdgeConnectorList{value: val, isSet: true}
}

func (v NullablePaginatedResponseListBaseEdgeConnectorList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseListBaseEdgeConnectorList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


