/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the TLSWorkloadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TLSWorkloadRequest{}

// TLSWorkloadRequest struct for TLSWorkloadRequest
type TLSWorkloadRequest struct {
	Certificate NullableInt64 `json:"certificate,omitempty"`
	Ciphers NullableTLSWorkloadCiphers `json:"ciphers,omitempty"`
	MinimumVersion NullableTLSWorkloadMinimumVersion `json:"minimum_version,omitempty"`
}

// NewTLSWorkloadRequest instantiates a new TLSWorkloadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTLSWorkloadRequest() *TLSWorkloadRequest {
	this := TLSWorkloadRequest{}
	return &this
}

// NewTLSWorkloadRequestWithDefaults instantiates a new TLSWorkloadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTLSWorkloadRequestWithDefaults() *TLSWorkloadRequest {
	this := TLSWorkloadRequest{}
	return &this
}

// GetCertificate returns the Certificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TLSWorkloadRequest) GetCertificate() int64 {
	if o == nil || IsNil(o.Certificate.Get()) {
		var ret int64
		return ret
	}
	return *o.Certificate.Get()
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TLSWorkloadRequest) GetCertificateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Certificate.Get(), o.Certificate.IsSet()
}

// HasCertificate returns a boolean if a field has been set.
func (o *TLSWorkloadRequest) HasCertificate() bool {
	if o != nil && o.Certificate.IsSet() {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given NullableInt64 and assigns it to the Certificate field.
func (o *TLSWorkloadRequest) SetCertificate(v int64) {
	o.Certificate.Set(&v)
}
// SetCertificateNil sets the value for Certificate to be an explicit nil
func (o *TLSWorkloadRequest) SetCertificateNil() {
	o.Certificate.Set(nil)
}

// UnsetCertificate ensures that no value is present for Certificate, not even an explicit nil
func (o *TLSWorkloadRequest) UnsetCertificate() {
	o.Certificate.Unset()
}

// GetCiphers returns the Ciphers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TLSWorkloadRequest) GetCiphers() TLSWorkloadCiphers {
	if o == nil || IsNil(o.Ciphers.Get()) {
		var ret TLSWorkloadCiphers
		return ret
	}
	return *o.Ciphers.Get()
}

// GetCiphersOk returns a tuple with the Ciphers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TLSWorkloadRequest) GetCiphersOk() (*TLSWorkloadCiphers, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ciphers.Get(), o.Ciphers.IsSet()
}

// HasCiphers returns a boolean if a field has been set.
func (o *TLSWorkloadRequest) HasCiphers() bool {
	if o != nil && o.Ciphers.IsSet() {
		return true
	}

	return false
}

// SetCiphers gets a reference to the given NullableTLSWorkloadCiphers and assigns it to the Ciphers field.
func (o *TLSWorkloadRequest) SetCiphers(v TLSWorkloadCiphers) {
	o.Ciphers.Set(&v)
}
// SetCiphersNil sets the value for Ciphers to be an explicit nil
func (o *TLSWorkloadRequest) SetCiphersNil() {
	o.Ciphers.Set(nil)
}

// UnsetCiphers ensures that no value is present for Ciphers, not even an explicit nil
func (o *TLSWorkloadRequest) UnsetCiphers() {
	o.Ciphers.Unset()
}

// GetMinimumVersion returns the MinimumVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TLSWorkloadRequest) GetMinimumVersion() TLSWorkloadMinimumVersion {
	if o == nil || IsNil(o.MinimumVersion.Get()) {
		var ret TLSWorkloadMinimumVersion
		return ret
	}
	return *o.MinimumVersion.Get()
}

// GetMinimumVersionOk returns a tuple with the MinimumVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TLSWorkloadRequest) GetMinimumVersionOk() (*TLSWorkloadMinimumVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinimumVersion.Get(), o.MinimumVersion.IsSet()
}

// HasMinimumVersion returns a boolean if a field has been set.
func (o *TLSWorkloadRequest) HasMinimumVersion() bool {
	if o != nil && o.MinimumVersion.IsSet() {
		return true
	}

	return false
}

// SetMinimumVersion gets a reference to the given NullableTLSWorkloadMinimumVersion and assigns it to the MinimumVersion field.
func (o *TLSWorkloadRequest) SetMinimumVersion(v TLSWorkloadMinimumVersion) {
	o.MinimumVersion.Set(&v)
}
// SetMinimumVersionNil sets the value for MinimumVersion to be an explicit nil
func (o *TLSWorkloadRequest) SetMinimumVersionNil() {
	o.MinimumVersion.Set(nil)
}

// UnsetMinimumVersion ensures that no value is present for MinimumVersion, not even an explicit nil
func (o *TLSWorkloadRequest) UnsetMinimumVersion() {
	o.MinimumVersion.Unset()
}

func (o TLSWorkloadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TLSWorkloadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Certificate.IsSet() {
		toSerialize["certificate"] = o.Certificate.Get()
	}
	if o.Ciphers.IsSet() {
		toSerialize["ciphers"] = o.Ciphers.Get()
	}
	if o.MinimumVersion.IsSet() {
		toSerialize["minimum_version"] = o.MinimumVersion.Get()
	}
	return toSerialize, nil
}

type NullableTLSWorkloadRequest struct {
	value *TLSWorkloadRequest
	isSet bool
}

func (v NullableTLSWorkloadRequest) Get() *TLSWorkloadRequest {
	return v.value
}

func (v *NullableTLSWorkloadRequest) Set(val *TLSWorkloadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTLSWorkloadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTLSWorkloadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTLSWorkloadRequest(val *TLSWorkloadRequest) *NullableTLSWorkloadRequest {
	return &NullableTLSWorkloadRequest{value: val, isSet: true}
}

func (v NullableTLSWorkloadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTLSWorkloadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


