/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the FileUploadSensitivityEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileUploadSensitivityEnum{}

// FileUploadSensitivityEnum * `lowest` - lowest * `low` - low * `medium` - medium * `high` - high * `highest` - highest
type FileUploadSensitivityEnum struct {
}

// NewFileUploadSensitivityEnum instantiates a new FileUploadSensitivityEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileUploadSensitivityEnum() *FileUploadSensitivityEnum {
	this := FileUploadSensitivityEnum{}
	return &this
}

// NewFileUploadSensitivityEnumWithDefaults instantiates a new FileUploadSensitivityEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileUploadSensitivityEnumWithDefaults() *FileUploadSensitivityEnum {
	this := FileUploadSensitivityEnum{}
	return &this
}

func (o FileUploadSensitivityEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileUploadSensitivityEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableFileUploadSensitivityEnum struct {
	value FileUploadSensitivityEnum
	isSet bool
}

func (v NullableFileUploadSensitivityEnum) Get() FileUploadSensitivityEnum {
	return v.value
}

func (v *NullableFileUploadSensitivityEnum) Set(val FileUploadSensitivityEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableFileUploadSensitivityEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableFileUploadSensitivityEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileUploadSensitivityEnum(val FileUploadSensitivityEnum) *NullableFileUploadSensitivityEnum {
	return &NullableFileUploadSensitivityEnum{value: val, isSet: true}
}

func (v NullableFileUploadSensitivityEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileUploadSensitivityEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


