/*
Accounts API

Testing AccountsInfoAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package accounts

import (
	"context"
	"testing"

	openapiclient "github.com/aziontech/azionapi-v4-go-sdk/accounts-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_accounts_api_AccountsInfoAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AccountsInfoAPIService RetrieveAccountInfoDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id int32

		resp, httpRes, err := apiClient.AccountsInfoAPI.RetrieveAccountInfoDetails(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsInfoAPIService UpdateAccountInfoDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id int32

		resp, httpRes, err := apiClient.AccountsInfoAPI.UpdateAccountInfoDetails(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
