/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the ResponseBadRequestEdgeFirewallFunctionInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseBadRequestEdgeFirewallFunctionInstance{}

// ResponseBadRequestEdgeFirewallFunctionInstance struct for ResponseBadRequestEdgeFirewallFunctionInstance
type ResponseBadRequestEdgeFirewallFunctionInstance struct {
	Id []string `json:"id,omitempty"`
	LastEditor []string `json:"last_editor,omitempty"`
	LastModified []string `json:"last_modified,omitempty"`
	Name []string `json:"name,omitempty"`
	JsonArgs []string `json:"json_args,omitempty"`
	EdgeFunction []string `json:"edge_function,omitempty"`
	Active []string `json:"active,omitempty"`
	Detail *string `json:"detail,omitempty" validate:"regexp=.*"`
}

// NewResponseBadRequestEdgeFirewallFunctionInstance instantiates a new ResponseBadRequestEdgeFirewallFunctionInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseBadRequestEdgeFirewallFunctionInstance() *ResponseBadRequestEdgeFirewallFunctionInstance {
	this := ResponseBadRequestEdgeFirewallFunctionInstance{}
	return &this
}

// NewResponseBadRequestEdgeFirewallFunctionInstanceWithDefaults instantiates a new ResponseBadRequestEdgeFirewallFunctionInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseBadRequestEdgeFirewallFunctionInstanceWithDefaults() *ResponseBadRequestEdgeFirewallFunctionInstance {
	this := ResponseBadRequestEdgeFirewallFunctionInstance{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetId() []string {
	if o == nil || IsNil(o.Id) {
		var ret []string
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetIdOk() ([]string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given []string and assigns it to the Id field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetId(v []string) {
	o.Id = v
}

// GetLastEditor returns the LastEditor field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetLastEditor() []string {
	if o == nil || IsNil(o.LastEditor) {
		var ret []string
		return ret
	}
	return o.LastEditor
}

// GetLastEditorOk returns a tuple with the LastEditor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetLastEditorOk() ([]string, bool) {
	if o == nil || IsNil(o.LastEditor) {
		return nil, false
	}
	return o.LastEditor, true
}

// HasLastEditor returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasLastEditor() bool {
	if o != nil && !IsNil(o.LastEditor) {
		return true
	}

	return false
}

// SetLastEditor gets a reference to the given []string and assigns it to the LastEditor field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetLastEditor(v []string) {
	o.LastEditor = v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetLastModified() []string {
	if o == nil || IsNil(o.LastModified) {
		var ret []string
		return ret
	}
	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetLastModifiedOk() ([]string, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given []string and assigns it to the LastModified field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetLastModified(v []string) {
	o.LastModified = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetName() []string {
	if o == nil || IsNil(o.Name) {
		var ret []string
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetNameOk() ([]string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given []string and assigns it to the Name field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetName(v []string) {
	o.Name = v
}

// GetJsonArgs returns the JsonArgs field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetJsonArgs() []string {
	if o == nil || IsNil(o.JsonArgs) {
		var ret []string
		return ret
	}
	return o.JsonArgs
}

// GetJsonArgsOk returns a tuple with the JsonArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetJsonArgsOk() ([]string, bool) {
	if o == nil || IsNil(o.JsonArgs) {
		return nil, false
	}
	return o.JsonArgs, true
}

// HasJsonArgs returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasJsonArgs() bool {
	if o != nil && !IsNil(o.JsonArgs) {
		return true
	}

	return false
}

// SetJsonArgs gets a reference to the given []string and assigns it to the JsonArgs field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetJsonArgs(v []string) {
	o.JsonArgs = v
}

// GetEdgeFunction returns the EdgeFunction field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetEdgeFunction() []string {
	if o == nil || IsNil(o.EdgeFunction) {
		var ret []string
		return ret
	}
	return o.EdgeFunction
}

// GetEdgeFunctionOk returns a tuple with the EdgeFunction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetEdgeFunctionOk() ([]string, bool) {
	if o == nil || IsNil(o.EdgeFunction) {
		return nil, false
	}
	return o.EdgeFunction, true
}

// HasEdgeFunction returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasEdgeFunction() bool {
	if o != nil && !IsNil(o.EdgeFunction) {
		return true
	}

	return false
}

// SetEdgeFunction gets a reference to the given []string and assigns it to the EdgeFunction field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetEdgeFunction(v []string) {
	o.EdgeFunction = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetActive() []string {
	if o == nil || IsNil(o.Active) {
		var ret []string
		return ret
	}
	return o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetActiveOk() ([]string, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given []string and assigns it to the Active field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetActive(v []string) {
	o.Active = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ResponseBadRequestEdgeFirewallFunctionInstance) SetDetail(v string) {
	o.Detail = &v
}

func (o ResponseBadRequestEdgeFirewallFunctionInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseBadRequestEdgeFirewallFunctionInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastEditor) {
		toSerialize["last_editor"] = o.LastEditor
	}
	if !IsNil(o.LastModified) {
		toSerialize["last_modified"] = o.LastModified
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.JsonArgs) {
		toSerialize["json_args"] = o.JsonArgs
	}
	if !IsNil(o.EdgeFunction) {
		toSerialize["edge_function"] = o.EdgeFunction
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	return toSerialize, nil
}

type NullableResponseBadRequestEdgeFirewallFunctionInstance struct {
	value *ResponseBadRequestEdgeFirewallFunctionInstance
	isSet bool
}

func (v NullableResponseBadRequestEdgeFirewallFunctionInstance) Get() *ResponseBadRequestEdgeFirewallFunctionInstance {
	return v.value
}

func (v *NullableResponseBadRequestEdgeFirewallFunctionInstance) Set(val *ResponseBadRequestEdgeFirewallFunctionInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseBadRequestEdgeFirewallFunctionInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseBadRequestEdgeFirewallFunctionInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseBadRequestEdgeFirewallFunctionInstance(val *ResponseBadRequestEdgeFirewallFunctionInstance) *NullableResponseBadRequestEdgeFirewallFunctionInstance {
	return &NullableResponseBadRequestEdgeFirewallFunctionInstance{value: val, isSet: true}
}

func (v NullableResponseBadRequestEdgeFirewallFunctionInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseBadRequestEdgeFirewallFunctionInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


