/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge

import (
	"encoding/json"
)

// checks if the PaginatedResponseListErrorResponsesList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseListErrorResponsesList{}

// PaginatedResponseListErrorResponsesList struct for PaginatedResponseListErrorResponsesList
type PaginatedResponseListErrorResponsesList struct {
	Count *int32 `json:"count,omitempty"`
	Results []ResponseListErrorResponses `json:"results,omitempty"`
}

// NewPaginatedResponseListErrorResponsesList instantiates a new PaginatedResponseListErrorResponsesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseListErrorResponsesList() *PaginatedResponseListErrorResponsesList {
	this := PaginatedResponseListErrorResponsesList{}
	return &this
}

// NewPaginatedResponseListErrorResponsesListWithDefaults instantiates a new PaginatedResponseListErrorResponsesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseListErrorResponsesListWithDefaults() *PaginatedResponseListErrorResponsesList {
	this := PaginatedResponseListErrorResponsesList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedResponseListErrorResponsesList) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListErrorResponsesList) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedResponseListErrorResponsesList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PaginatedResponseListErrorResponsesList) SetCount(v int32) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedResponseListErrorResponsesList) GetResults() []ResponseListErrorResponses {
	if o == nil || IsNil(o.Results) {
		var ret []ResponseListErrorResponses
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListErrorResponsesList) GetResultsOk() ([]ResponseListErrorResponses, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedResponseListErrorResponsesList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ResponseListErrorResponses and assigns it to the Results field.
func (o *PaginatedResponseListErrorResponsesList) SetResults(v []ResponseListErrorResponses) {
	o.Results = v
}

func (o PaginatedResponseListErrorResponsesList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseListErrorResponsesList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedResponseListErrorResponsesList struct {
	value *PaginatedResponseListErrorResponsesList
	isSet bool
}

func (v NullablePaginatedResponseListErrorResponsesList) Get() *PaginatedResponseListErrorResponsesList {
	return v.value
}

func (v *NullablePaginatedResponseListErrorResponsesList) Set(val *PaginatedResponseListErrorResponsesList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseListErrorResponsesList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseListErrorResponsesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseListErrorResponsesList(val *PaginatedResponseListErrorResponsesList) *NullablePaginatedResponseListErrorResponsesList {
	return &NullablePaginatedResponseListErrorResponsesList{value: val, isSet: true}
}

func (v NullablePaginatedResponseListErrorResponsesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseListErrorResponsesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


