name: Auto Merge PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened
      - opened
      - ready_for_review

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Check PR mergeability
      - name: Check PR status
        id: pr-check
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const mergeable = pr.data.mergeable;
            const state = pr.data.mergeable_state;

            if (!mergeable || state !== 'clean') {
              core.setFailed(`PR is not mergeable: mergeable=${mergeable}, state=${state}`);
            }

      # Automatically merge the PR if checks have passed
      - name: Merge the pull request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
