name: Generate SDKs

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  generate_sdk:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'patch')
    name: Generate SDK and commit to repo
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y npm curl git
        shell: bash

      - name: Install GH CLI
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y
        shell: bash

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install openapi-generator
        run: npm install @openapitools/openapi-generator-cli -g
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get Changed .yml Files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.yaml$' | xargs)" >> $GITHUB_OUTPUT

      - name: Run OpenAPI Generator for Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            removed=$(basename "$file" .yml)
            npx @openapitools/openapi-generator-cli generate -i "$file" -g go -o "./generated/${removed}" --package-name "${removed}"
            echo 'go.mod' >> "./generated/${removed}/.gitignore"
            echo 'go.sum' >> "./generated/${removed}/.gitignore"
          done

      - name: Commit and Push Changes
        run: |
          git config user.email "patrick.menoti@gmail.com"
          git config user.name "PatrickMenoti"
          git checkout main
          git add generated/
          if git diff --cached --quiet; then
            echo "::warning::No changes detected. Skipping commit."
          else
            git commit -m "Auto-Generated SDKs based on merged PR"
            git push origin main
          fi
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  bump:
      needs: generate_sdk
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
  
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.37.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            RELEASE_BRANCHES: main
            WITH_V: true
